// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk06ZEQ29sF0kNRg5tJpUNFt29tXRI9Hw',
    appId: '1:973193718497:web:a8f20a59f2cbb39ad925a0',
    messagingSenderId: '973193718497',
    projectId: 'pulsr-24243',
    authDomain: 'pulsr-24243.firebaseapp.com',
    storageBucket: 'pulsr-24243.firebasestorage.app',
    measurementId: 'G-XQ3B3CSKYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrGrDfNYj-17_eZ0rHPPo2tuwQA8A_O64',
    appId: '1:973193718497:android:742e8a240c53f1e5d925a0',
    messagingSenderId: '973193718497',
    projectId: 'pulsr-24243',
    storageBucket: 'pulsr-24243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxrqWJ4MvsYIo41l5jtjnZHYkt5sOv6UQ',
    appId: '1:973193718497:ios:4769a3033488b146d925a0',
    messagingSenderId: '973193718497',
    projectId: 'pulsr-24243',
    storageBucket: 'pulsr-24243.firebasestorage.app',
    iosClientId:
        '973193718497-bb716okvnhklii03mimq4pv5pdfjaveg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulsr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxrqWJ4MvsYIo41l5jtjnZHYkt5sOv6UQ',
    appId: '1:973193718497:ios:4769a3033488b146d925a0',
    messagingSenderId: '973193718497',
    projectId: 'pulsr-24243',
    storageBucket: 'pulsr-24243.firebasestorage.app',
    iosClientId:
        '973193718497-bb716okvnhklii03mimq4pv5pdfjaveg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pulsr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk06ZEQ29sF0kNRg5tJpUNFt29tXRI9Hw',
    appId: '1:973193718497:web:158b624db3f6f569d925a0',
    messagingSenderId: '973193718497',
    projectId: 'pulsr-24243',
    authDomain: 'pulsr-24243.firebaseapp.com',
    storageBucket: 'pulsr-24243.firebasestorage.app',
    measurementId: 'G-E8LPR3PPN8',
  );
}
